apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.projectName  }}-secret"
type: Opaque
data:
    {{-$path := printf "certs/%s/*" .Values.env }}
    {{ (.File.Glob $path).AsSecrets | indent 2 }}
